### PR TITLE
Save while navigating - Course creation and updating

### PR DESCRIPTION
**Pull request by magnusklundgren**
## Description

For this PBI we have rewritten the way course data is sent to the backend when creating or updating course data. 
Previously things were created instantly in the database and sent individually. Now we sent an entire course and save it properly.

_There is a pull request for frontend where the data is cached and sent in the new format to backend. They can be reviewed separately_

## Changes
- Created two (2) new endpoints /api/courses/create/new and /api/courses/update/:id
- Added courseHelpers.js with two (2) main functions, createAndSaveCourse and updateAndSaveCourse. 
- The data sent is organized into mongoose objects and saved in their respective collections, while linking to each other.
- The updateAndSaveCourse function has a "naive" approach where it updates all the data, even if the data is identical. And only compares which data exists, e.g. which sections, new/deleted etc.
- Added new error codes to throw meaningful errors.
- Media is now saved on the backend whereas it was previously done directly from the frontend. This is incorporated in the process

## Related Issues
https://github.com/orgs/Educado-App/projects/14/views/12?pane=issue&itemId=82190855&issue=Educado-App%7Ceducado-frontend%7C142

## Checklist

- [x] Code has been tested locally and passes all relevant tests. (tests implemented, jest issues with loading FormData)
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.
- [x] Changes have been approved by Product Owner
- [x] Code has been analyzed with CodeScene
- [x] I have reviewed the pull request myself

## Link to documentation
Link to any relevant documentation related to this PR

## Notes for Reviewers
We realise this is quite a bit of lines, but a lot of it follows similar logic, don't be scared. 
Look under **__tests__/fixtures/fakeCourseCreationData** and **fakeCourseUpdateData** to see how the data is organized when we get it from frontend.

### CODE REVIEW

**Review by MartinJenzen — APPROVED** [review]
I haven't tested the functionality, but apart from a few _minor_ details, the code is otherwise absolutely immaculate and very well written - it looks professional! The code is clean and very readable. You get two thumbs-up 👍👍

**Comment by magnusklundgren** [comment]
Thanks for the nice feedback, resolved the comments :) 👍

**Review by MartinJenzen — APPROVED** [review]
As Borat would have said: "Very niiice!" 👍😀👍

**Review by MartinJenzen — APPROVED** [review]
👍

**Pull request merged**
