### PR TITLE
[App Components] Fix flow for components

### PR DESCRIPTION
**Pull request by loui981c**
## Description

Look at the PR  [App Components] Fix flow for components #194 in Mobile

## Checklist

- [X] Code has been tested locally and passes all relevant tests.
- [X] Documentation has been updated to reflect the changes, if applicable.
- [X] Code follows the established coding style and guidelines of the project.
- [X] All new and existing tests related to the changes have passed.
- [X] Any necessary dependencies or new packages have been properly documented.
- [X] Pull request title and description are clear and descriptive.
- [X] Reviewers have been assigned to the pull request.
- [X] Any potential security implications have been considered and addressed.
- [X] Performance impact of the changes has been evaluated, if relevant.

### CODE REVIEW

**Review by PrometheusBork — CHANGES_REQUESTED** [review]
Does not work properly with dev mobile, in explorescreen I get constant  E0014 "Invalid id", seems to be an error for checking if a course is subscribed.

**Review by Donhusum — APPROVED** [review]
Have not been linted, but otherwise looks good

**Comment by loui981c** [comment]
is it a new user or old one? also the only section with updated structure is the last one of in the course finance course

**Comment by PrometheusBork** [comment]
It has student models and works with dev backend but not with this one

**Review by ITPini — CHANGES_REQUESTED** [review]
Backend crashes with the new changes from your new mobile PR when entering a lecture
```
CastError: Cast to ObjectId failed for value "undefined" (type string) at path "_id" for model "exercises"
    at model.Query.exec (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/query.js:4498:21)
    at Query.then (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/query.js:4592:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  messageFormat: undefined,
  stringValue: '"undefined"',
  kind: 'ObjectId',
  value: 'undefined',
  path: '_id',
  reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
      at new ObjectID (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/node_modules/bson/lib/bson/objectid.js:59:11)
      at castObjectId (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/cast/objectid.js:25:12)
      at ObjectId.cast (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/schema/objectid.js:246:12)
      at SchemaType.applySetters (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/schematype.js:1123:12)
      at SchemaType._castForQuery (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/schematype.js:1601:15)
      at SchemaType.castForQuery (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/schematype.js:1591:15)
      at SchemaType.castForQueryWrapper (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/schematype.js:1568:20)
      at cast (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/cast.js:332:32)
      at Query.cast (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/query.js:4937:12)
      at Query._castConditions (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/query.js:1975:10)
      at model.Query.<anonymous> (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/query.js:2232:8)
      at model.Query._wrappedThunk [as _findOne] (/Users/patrickpini/Documents/GitHub/educado-backend/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
      at /Users/patrickpini/Documents/GitHub/educado-backend/node_modules/kareem/index.js:370:33
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11),
  valueType: 'string'
}
```

**Review by Donhusum — CHANGES_REQUESTED** [review]
Does not work

**Review by JackSMunn — APPROVED** [review]
Looks good, lets go

**Review by ITPini — APPROVED** [review]

**Review by ITPini — APPROVED** [review]

**Review by Donhusum — APPROVED** [review]
Yes

**Pull request merged**
