### PR TITLE
Onboarding - Login and Signup

### PR DESCRIPTION
**Pull request by Adachigaming**
### Description
This pull request is the complete backend functionality of the relevant PBIs of the Onboarding team.

### Changes
- Added new routing for Login and Signup post requests: they are now handled in credentialsRoutes.js.
- Changed the models of the ContencCreators to match the newer specifications, i.e. removed "motivation" and made "firstname" and "lastname" one field.
- Added token creation upon receiving a login POST request in credentialsRouts.js, which the frontend is able to make use of,
- Added hashing of password, which are handled in credentialsRoutes.js.
- Added error messages that the frontend login page can use when invalid credentials are used, also in credentialsRouts.js.

Additionally, there are no new dependencies.

### Related Issues
There are no related issues to the above functionalities.

### Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x]  Code follows the established coding style and guidelines of the project.
- [x]  All new and existing tests related to the changes have passed.
- [x]  Any necessary dependencies or new packages have been properly documented.
- [x]  Pull request title and description are clear and descriptive.
- [x]  Reviewers have been assigned to the pull request.
- [x]  Any potential security implications have been considered and addressed.
- [x]  Performance impact of the changes has been evaluated, if relevant.

### CODE REVIEW

**Comment by JackSMunn** [comment]
Ping when ready for review.

**Comment by Jatewo** [comment]
Before reviewing:

- The checklist says you have not considered any security implications. I think this would be a very relevant thing to consider, especially in the backend. Could you perhaps discuss the security aspect and address it if there are any problems. A note to the reviewer or in the description would be fine in most cases, since security is not necessary for the application to run, and the focus is not on security right now but sometimes it may be a good idea to make some changes right away so as not to expose the whole system.
- You have some conflicts, which should be resolved asap to avoid a lot of changes after reviews
- For future PRs, a more specific description would be nice 😃

**Comment by Adachigaming** [comment]
> Before reviewing:
> 
> * The checklist says you have not considered any security implications. I think this would be a very relevant thing to consider, especially in the backend. Could you perhaps discuss the security aspect and address it if there are any problems. A note to the reviewer or in the description would be fine in most cases, since security is not necessary for the application to run, and the focus is not on security right now but sometimes it may be a good idea to make some changes right away so as not to expose the whole system.
> * You have some conflicts, which should be resolved asap to avoid a lot of changes after reviews
> * For future PRs, a more specific description would be nice 😃

I believe the reason as to why we didn't mark it was that the token that gets created isn't really used for more than surface-level validation. The issue is mainly in the frontend, which we haven't finished just yet. I'll go ahead and check it, since we have discussed it.

**Comment by Jatewo** [comment]
> > Before reviewing:
> > 
> > * The checklist says you have not considered any security implications. I think this would be a very relevant thing to consider, especially in the backend. Could you perhaps discuss the security aspect and address it if there are any problems. A note to the reviewer or in the description would be fine in most cases, since security is not necessary for the application to run, and the focus is not on security right now but sometimes it may be a good idea to make some changes right away so as not to expose the whole system.
> > * You have some conflicts, which should be resolved asap to avoid a lot of changes after reviews
> > * For future PRs, a more specific description would be nice 😃
> 
> I believe the reason as to why we didn't mark it was that the token that gets created isn't really used for more than surface-level validation. The issue is mainly in the frontend, which we haven't finished just yet. I'll go ahead and check it, since we have discussed it.

All good 👍

**Review by JackSMunn — CHANGES_REQUESTED** [review]
See comments regarding errors. Swap to new error system, which can be found in resources/ERRORS.md 

Also, please be careful with routes. Only make new ones that we can refactor into the same routes later, dont delete or change in existing routes. 

Please add testing. If you are unsure of JEST, come talk to us. You can also see examples of JEST on DEV. 

Ping when you are done with changes and testing.

**Comment by MGLarsenSW** [comment]
closed and created again on, Onboarding - Login and Signup v2

**Pull request closed without merging**
