### PR TITLE
FIX: User model refactored

### PR DESCRIPTION
**Pull request by MortenMunk**
## Description

This PR fixes the problems related to courses, on the new merged User model.

## Changes

- replaced user db searches with student db searches in courseRoutes.test.js
- removed subscriptions field in users.js, as it is placed in students model now.
- replaced db interaction with users model, to students model in courseRoutes.js
- Removed all traces of signupRoutes, as this functionality is now happily stored in authRoutes 😏
- updated the way students are fetched in studentRoutes
- updated studentRoutes tests to match the updated way of fetching 😢 

## Related Issues

None.

## Checklist

- [X] Code has been tested locally and passes all relevant tests.
- [X] Documentation has been updated to reflect the changes, if applicable.
- [X] Code follows the established coding style and guidelines of the project.
- [X] All new and existing tests related to the changes have passed.
- [X] Any necessary dependencies or new packages have been properly documented.
- [X] Pull request title and description are clear and descriptive.
- [X] Reviewers have been assigned to the pull request.
- [X] Any potential security implications have been considered and addressed.
- [X] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)

None relevant.

## If mobile/frontend pull request, what version of the backend is it stable, and running on? 

Commit id: 0a7ba5b1a21e56b3420f85c7d7ea4100d61260b5

## Notes for Reviewers

**PLEASE NOTE THAT THIS IS A FIX, SO THE MERGED USER MODEL NOW WORKS WITH COURSES AGAIN.
PLEASE CHECK ON THE APP THAT COURSES ARE DISPLAYED CORRECTLY WHEN LOGGED IN, IF YOU HAVE ANY COURSES IN YOUR DATABASE**

Registering a user, on mobile does not work with the backend right now, but I am also currently fixing this in another PR 😄

### CODE REVIEW

**Review by MagnusHArnvind — APPROVED** [review]

**Review by Mafusn — APPROVED** [review]
Looks great

**Review by Donhusum — APPROVED** [review]
All the changes look fine. My only question is if userRoute don't need the same changes. It might not.

**Review by Mafusn — APPROVED** [review]
Looks great, i the routes in studenRoutes for answering exercises still work as intended

**Review by PrometheusBork — APPROVED** [review]
Looks great and works great with dev mobile!

**Pull request merged**
