### PR TITLE
Dev to staging

### PR DESCRIPTION
**Pull request by Mafusn**
## Description

Created a new route which takes a new and an old password, checks that the old password is correct and the new password is valid and then changes the password for the user. Logic for points when answering exercises.

## Changes

- Added two error codes
- Added route for changing password (requiring an old and a new password)
- Added tests for change password route
- Updated the studentmodel to show completionDate for exercises, sections and courses.
- Implemented logic for answering exercises and give points based thereof

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

### CODE REVIEW

**Comment by PrometheusBork** [comment]
When I run the backend with staging in mobile, you cannot subscribe or unsubscribe from courses

**Comment by Mafusn** [comment]
> When I run the backend with staging in mobile, you cannot subscribe or unsubscribe from courses
@Vagn99 @carlryskov

**Comment by PrometheusBork** [comment]
Cannot register a new user when using this backend with staging mobile

**Review by MGLarsenSW — CHANGES_REQUESTED** [review]
Why is credentialRoutes and the relevant test removed? They are being used

**Review by Donhusum — CHANGES_REQUESTED** [review]
This should not be merged to staging before the changes to userModel is fixed. A PR with the fixes to dev have already been made, when it is approved it should be included in this PR

**Review by JackSMunn — APPROVED** [review]

**Pull request closed without merging**
